import React, {useState, useEffect} from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Feed } from "feed";


export default function Home() {

  const [products, setProducts] = useState([]);

  const feed = new Feed({
    title: "Feed Title",
    description: "This is my personal feed!",
    id: "http://example.com/",
    link: "http://example.com/",
    language: "en", // optional, used only in RSS 2.0, possible values: http://www.w3.org/TR/REC-html40/struct/dirlang.html#langcodes
    image: "http://example.com/image.png",
    favicon: "http://example.com/favicon.ico",
    copyright: "All rights reserved 2013, John Doe",
    updated: new Date(2013, 6, 14), // optional, default = today
    generator: "awesome", // optional, default = 'Feed for Node.js'
    feedLinks: {
      json: "https://example.com/json",
      atom: "https://example.com/atom",
    },
    author: {
      name: "John Doe",
      email: "johndoe@example.com",
      link: "https://example.com/johndoe",
    },
  });

 

  useEffect(() => {
    fetch("https://fakestoreapi.com/products?limit=5")
    .then((res) => res.json())
    .then((json) => setProducts(json));
  }, []);

  products.forEach(product => {
    feed.addItem({
      title: product.title,
      id: product.id,
      link: "www.olle.se",
      description: product.description,
      author: [
        {
          name: "Jane Doe",
          email: "janedoe@example.com",
          link: "https://example.com/janedoe"
        },
        {
          name: "Joe Smith",
          email: "joesmith@example.com",
          link: "https://example.com/joesmith"
        }
      ],
      contributor: [
        {
          name: "Shawn Kemp",
          email: "shawnkemp@example.com",
          link: "https://example.com/shawnkemp"
        },
        {
          name: "Reggie Miller",
          email: "reggiemiller@example.com",
          link: "https://example.com/reggiemiller"
        }
      ],
      image: product.image
    });
  });

  console.log(products);
  console.log(feed.rss2());

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>Hello</main>
    </div>
  );
}
